### ISSUE TITLE
建议使用 url_for 函数配合重定向使用

### ISSUE THREAD

**Issue by Swinggcat** [Tank1e/Program-Board#1]
https://github.com/Tank1e/Program-Board/blob/d5461faa8eda3c4b9d3f2fe03c02d3481897d04a/min-program.py#L18

此处可以使用 `redirect(url_for('commit'))` 来替代。

请务必避免在代码中硬编码路径。

**Comment by Tank1e** [comment]
proxy后反向代理后redirect，返回的到浏览器的地址是真实服务器地址 的问题还没有解决：
浏览器POST方法 122.51.48.86，浏览器会redirect到http://127.0.0.1:3000/commit
暂时不能改，谢谢支持。

**Comment by Swinggcat** [comment]
这说明你没有配置 ProxyPassReverse。

**Comment by Tank1e** [comment]
问题已经都解决了，谢谢！
