### ISSUE TITLE
警告：服务器上请禁用 mysql root 用户远程登陆

### ISSUE THREAD

**Issue by DuckSoft** [Tank1e/Program-Board#2]
https://github.com/Tank1e/Program-Board/blob/d5461faa8eda3c4b9d3f2fe03c02d3481897d04a/min-program.py#L61

用户名和密码被硬编码进代码仓库中。请避免允许 root 用户远程登陆 mysql，否则数据安全难保。

**Comment by Tank1e** [comment]
已经检查了user host。谢谢支持。
